config/routes.rb
GurPhoto::Application.routes.draw do
  root :to => 'site#index'

  match '/page/:alias' => 'pages#show', as: :show_page
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :documents do
    member do
      get :sort
    end
  end

  resources :email_templates
  resources :articles
  resources :logs
  resources :profiles, except: :index
  resources :articles
  resources :pages

  resources :users do
    post :save_hotel_search_query, on: :member
  end

  resources :site do
    get :partners, on: :collection
  end

  resources :baskets, controller: 'BasketItems' do
    get :clear, on: :collection
  end

  resources :tickets do
    get :pull, on: :member
    get :close, on: :member

    resources :messages
  end

  resources :users do
    get :print, on: :member
  end

  namespace :user do
    resources :users
    resources :moderators
    resources :agencies
    resources :hoteliers
    resources :campers
  end

  resources :hotels do
    get :print, on: :member
    get :retval, on: :member
    #resources :hotelier_hotels
  end

  namespace :hotel do
    resources :reviews
    resources :import

    resources :cities do
      get :sort, on: :member
    end

    resources :services do
      get :sort, on: :member
    end

    resources :rooms do
      get :print, on: :member
    end

    resources :filters do
      get :sort, on: :member
    end

    namespace :service do
      resources :values
    end

    namespace :filter do
      resources :values
      resources :items
    end

    namespace :room do
      resources :fields do
        get :sort, on: :member
      end

      resources :lists do
        get :sort, on: :member
      end
    end
  end
 
#  resources :hotels do
#    member do
#      get :print
#    end
#
#    resources :rooms, controller: 'Hotel::Rooms'
#    resources :special_offers, controller: 'Hotel::SpecialOffers'
#
#    resources :images, controller: 'Hotel::Images' do
#      collection do
#        post :swfupload
#        get :swfupload
#      end
#    end
#  end

  devise_scope :user do
    get '/login' => 'sessions#new'
  end
  devise_for :users, :path_prefix => 'd', controllers: { unlocks: 'unlocks', sessions: 'sessions', passwords: 'passwords' }

end

app/models/hotel/filter/value.rb
class Hotel::Filter::Value < ActiveRecord::Base
  belongs_to :item
  belongs_to :filter

  attr_accessible :filter_id, :hotel_id, :name, :item_id
end

app/models/hotel/room/field/value.rb
# encoding: utf-8

class Hotel::Room::Field::Value < ActiveRecord::Base
  attr_accessible :field_id, :value

  belongs_to :field
  belongs_to :room

  validates :value, length: { maximum: 255 }
end

app/models/hotel/room/list/value.rb
class Hotel::Room::List::Value < ActiveRecord::Base
  attr_accessible :item_id, :list_id

  belongs_to :room
  belongs_to :list
  belongs_to :item

  validates :item_id, :list_id, presence: true
end

app/models/hotel/service.rb
class Hotel::Service < ActiveRecord::Base
  has_many :values
  default_scope order: 'position'

  attr_accessible :include_to_print, :name, :default_value, :default, :only_signed, :multiline, :filter_item_id, :only_moderator
  attr_accessible :position

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 255 }

  acts_as_list

  def self.values_for_hotel hotel_id
    joins "left join hotel_service_values on hotel_services.id = hotel_service_values.service_id and hotel_service_values.hotel_id = #{hotel_id}"
  end

  def self.published
    where(include_to_print: true)
  end

  after_destroy do
    Value.delete_all "service_id=#{id}"
  end
end

app/models/hotel/service/value.rb
# encoding: utf-8

class Hotel::Service::Value < ActiveRecord::Base
  belongs_to :service, validate: true
  belongs_to :hotel, validate: true

  attr_accessible :service_id, :hotel_id, :value

  validates_each :value do |record, attr, value|
    record.errors.add(attr, "поля \"#{record.service.name}\" в сервисах слишком длинное") if value.length > 255
  end

  def check= value
  end

  def check
    value.present? || (service && service.default) || false
  end

  def valuoe
    return super unless super.empty?
    service.default_value
  end
end

app/controllers/hotel/filter/values_controller.rb
class Hotel::Filter::ValuesController < InheritedResources::Base
  respond_to :html, :json
end

app/controllers/hotel/service/values_controller.rb
class Hotel::Service::ValuesController < InheritedResources::Base
end

app/controllers/hotel/services_controller.rb
class Hotel::ServicesController < SortableController
end

app/helpers/hotel/filter/values_helper.rb
module Hotel::Filter::ValuesHelper
end

app/helpers/hotel/service/values_helper.rb
module Hotel::Service::ValuesHelper
end

app/helpers/hotel/services_helper.rb
module Hotel::ServicesHelper
end

app/views/hotel/service/values/_form.html.haml
= form_for @hotel_service_value do |f|
  -if @hotel_service_value.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hotel_service_value.errors.count, "error")} prohibited this hotel_service_value from being saved:"
      %ul
        - @hotel_service_value.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :service_id
    = f.number_field :service_id
  .field
    = f.label :hotel_id
    = f.number_field :hotel_id
  .field
    = f.label :value
    = f.text_field :value
  .actions
    = f.submit 'Save'

app/views/hotel/service/values/edit.html.haml
%h1 Editing hotel_service_value

= render 'form'

= link_to 'Show', @hotel_service_value
\|
= link_to 'Back', hotel_service_values_path

app/views/hotel/service/values/index.html.haml
%h1 Listing hotel_service_values

%table
  %tr
    %th Service
    %th Hotel
    %th Value
    %th
    %th
    %th

  - @hotel_service_values.each do |hotel_service_value|
    %tr
      %td= hotel_service_value.service_id
      %td= hotel_service_value.hotel_id
      %td= hotel_service_value.value
      %td= link_to 'Show', hotel_service_value
      %td= link_to 'Edit', edit_hotel_service_value_path(hotel_service_value)
      %td= link_to 'Destroy', hotel_service_value, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Value', new_hotel_service_value_path

app/views/hotel/service/values/new.html.haml
%h1 New hotel_service_value

= render 'form'

= link_to 'Back', hotel_service_values_path

app/views/hotel/service/values/show.html.haml
%p#notice= notice

%p
  %b Service:
  = @hotel_service_value.service_id
%p
  %b Hotel:
  = @hotel_service_value.hotel_id
%p
  %b Value:
  = @hotel_service_value.value

= link_to 'Edit', edit_hotel_service_value_path(@hotel_service_value)
\|
= link_to 'Back', hotel_service_values_path