config/routes.rb
GurPhoto::Application.routes.draw do
  root :to => 'site#index'

  match '/page/:alias' => 'pages#show', as: :show_page
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :documents do
    member do
      get :sort
    end
  end

  resources :email_templates
  resources :articles
  resources :logs
  resources :profiles, except: :index
  resources :articles
  resources :pages

  resources :users do
    post :save_hotel_search_query, on: :member
  end

  resources :site do
    get :partners, on: :collection
  end

  resources :baskets, controller: 'BasketItems' do
    get :clear, on: :collection
  end

  resources :tickets do
    get :pull, on: :member
    get :close, on: :member

    resources :messages
  end

  resources :users do
    get :print, on: :member
  end

  namespace :user do
    resources :users
    resources :moderators
    resources :agencies
    resources :hoteliers
    resources :campers
  end

  resources :hotels do
    get :print, on: :member
    get :retval, on: :member
    #resources :hotelier_hotels
  end

  namespace :hotel do
    resources :reviews
    resources :import

    resources :cities do
      get :sort, on: :member
    end

    resources :services do
      get :sort, on: :member
    end

    resources :rooms do
      get :print, on: :member
    end

    resources :filters do
      get :sort, on: :member
    end

    namespace :service do
      resources :values
    end

    namespace :filter do
      resources :values
      resources :items
    end

    namespace :room do
      resources :fields do
        get :sort, on: :member
      end

      resources :lists do
        get :sort, on: :member
      end
    end
  end
 
#  resources :hotels do
#    member do
#      get :print
#    end
#
#    resources :rooms, controller: 'Hotel::Rooms'
#    resources :special_offers, controller: 'Hotel::SpecialOffers'
#
#    resources :images, controller: 'Hotel::Images' do
#      collection do
#        post :swfupload
#        get :swfupload
#      end
#    end
#  end

  devise_scope :user do
    get '/login' => 'sessions#new'
  end
  devise_for :users, :path_prefix => 'd', controllers: { unlocks: 'unlocks', sessions: 'sessions', passwords: 'passwords' }

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_attached_file :attach
  acts_as_list
  strip_attributes

  validates :name, presence: true, :length => { minimum: 5, maximum: 255 }
  validates :attach, :attachment_presence => true

  scope :recent, lambda { |count| limit(count) }
  default_scope order: 'position'

  attr_accessible :name, :attach, :description
  attr_accessible :position
end

app/controllers/documents_controller.rb
class DocumentsController < SortableController
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= nice_form_for @document, html: { class: 'form-horizontal' } do |f|
  = f.errors_for
  = f.text_field :name, class: 'input-xlarge'
  = f.text_area :description, class: 'input-xxlarge'
  = f.file_field :attach

  = f.actions do
    = f.submit 'Сохранить'
    = link_to 'Назад', documents_path, class: :btn

app/views/documents/_table.html.haml
%table
  - collection.each do |resource|
    - filename = resource.attach.url(resource.attach.default_style, false)
    = content_tag_for :tr, resource do
      %td.type(width="32")
        %span.icon.big{ class: "icon#{File.extname(filename).gsub('.', '-')}" }
      %td.name
        %h6= link_to resource.name, filename
        %p
          = resource.description

      %td.actions(width="70")
        - if can? :edit, resource
          = icon_link_to 'arrow-up', '', sort_document_path(resource, direction: :up), remote: true, data: { replace: '#content-table' }
          = icon_link_to 'arrow-down', '', sort_document_path(resource, direction: :down), remote: true, data: { replace: '#content-table' }
          = icon_link_to 'pencil', '', edit_resource_path(resource)

        - if can? :destroy, resource
          = icon_link_to 'trash', '', resource, confirm: 'Вы уверены, что хотите удалить этот документ?', method: :delete

      %td(width="35")
        = link_to filename do
          %i.icon.big.icon-download

app/views/documents/edit.html.haml
.documents-edit
  %h3= "Редактирование документа \"#{resource.name}\""
  = render 'form'

app/views/documents/index.html.haml
.documents
  %h1.with-button
    Документы
    - if can? :create, Document
      = link_to 'Новый документ', new_resource_path, class: 'btn btn-mini btn-success'


  #content-table
    = render partial: 'table'

app/views/documents/new.html.haml
.documents-new
  %h3 Новый документ
  = render 'form'

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @document.name

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path